apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-k8s-app.fullname" . }}
  labels:
    {{- include "hello-k8s-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hello-k8s-app.selectorLabels" . | nindent 4 }}
